### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by tony**

### CODE REVIEW

**Comment by mmtrt** [comment]
This was intentional I call riot as rito, anyways I'll merge it.

**Comment by tony** [comment]
@mmtrt Thank you for the project! Runs very well!

**Comment by mmtrt** [comment]
Yeah enjoy while it lasts since riot is adding kernel side anti cheat then no more league on linux that change will come next year I think.

**Comment by tony** [comment]
@mmtrt Is there any hope the "kernel side" anticheat will have an extension to work with Wine/Linux though?  Did Riot devs mention anything about WINE support ending, or is it just implied in kernel being involved? (After all, they do have a mac client)

**Comment by mmtrt** [comment]
Not that I know there might we see support for it in WINE but still we can hope for.

**Pull request merged**
